# Generated by Django 3.0 on 2019-12-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='date_back',
            new_name='number',
        ),
    ]
