# Generated by Django 3.0 on 2019-12-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_item_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('price',)},
        ),
    ]
