# Generated by Django 3.0 on 2020-01-20 07:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('habitat', models.TextField()),
                ('iucn_status', models.IntegerField(choices=[(1, 'Extinct'), (2, 'Extinct in the wild'), (3, 'Critically endangered'), (4, 'Endangered'), (5, 'Vulnerable'), (6, 'Near threatened'), (7, 'Least concern')])),
                ('number', models.TextField()),
                ('subspecies', models.IntegerField()),
                ('life_span', models.TextField()),
                ('size', models.TextField()),
                ('weight', models.TextField()),
                ('diet', models.TextField()),
                ('image', models.URLField()),
                ('bg', models.URLField()),
                ('bg2', models.URLField()),
            ],
            options={
                'ordering': ('iucn_status',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('cat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='back.Cat', verbose_name='Cat')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('email', models.EmailField(max_length=254)),
                ('stripetoken', models.TextField()),
                ('cat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='back.Cat', verbose_name='Cat')),
            ],
            options={
                'ordering': ['-date', 'email'],
            },
        ),
    ]
